package com.samplepage.Relevel.OOPS;

public class ExceptionPractice {

     /*   // Try and catch Example
        try{
            int dat = 10/0;
        }
        catch(ArithmeticException e){
            System.out.println(e);
        }
        System.out.println("rest the code....");

      */

        // Throw Example
  //  public static void calSquareRoot(int num){
   //     if (num<0){
   //         throw new ArithmeticException("Number is negative can't calculate ir's square root");
    //    }else{
    //        System.out.println("square root  "+ num+ " is "+ Math.pow(num,0.5));
    //    }
   // }

     //   calSquareRoot(-4);
     //   System.out.println("rest the code");

    //Throws Example
  //  public static int devide (int dividend, int divisor) throws ArithmeticException{
   //     int quotient = dividend/divisor;
    //    return quotient;
   // }
    //    try{
    //        System.out.println(devide(45,0));
    //    }catch (ArithmeticException E){
    //        System.out.println("Arithmeyic Exception When you are trying to divide by zero");
    //    }

// Multiple Catch Example 1
public static void main(String[] args){
       // try {
       //     int arr[] = new int[10];
       //     arr[11] = 30/1;
       // }catch(ArithmeticException e){
       //     System.out.println(e.getMessage());
      //  }catch (ArrayIndexOutOfBoundsException E){
      //      System.out.println(E.getMessage());
      //

    }
}
